---
title: "seasonal_abalone_maturity"
author: "Craig Mundy and Malcolm Haddon"
date: "`r format(Sys.time(), '%d&period; %B %Y')`"
output: 
    word_document:
      reference_docx:  C:\Users\User\Dropbox\A_Book\book\trialreferencestyle.docx
      toc: true
      toc_depth: 3
      fig_caption: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE)

options(knitr.kable.NA = "",
        knitr.table.format = "pandoc")

if (dir.exists("C:/Users/Malcolm/Dropbox")) {
  ddir <- "C:/Users/Malcolm/Dropbox"
} else {
  ddir <- "C:/Users/User/Dropbox"
}

wkdir <- paste0(ddir,"/rcode2/rforcpue/data-raw/")

options("show.signif.stars"=FALSE,"stringsAsFactors"=FALSE,
        "max.print"=50000,"width"=240)

library(rutilsMH)
library(knitr)
library(captioner)
library(biology)    # https://github.com/haddonm

tab_nums <- captioner(prefix = "Table")
fig_nums <- captioner(prefix = "Figure")
equ_nums <- captioner(prefix = "Equ.")

#source(file.path("./../../A_Book/book/Rcpp_functions.R"))

```

# Seasonal variation in blacklip abalone maturity and its implications for choosing Legal Minimum Lengths

Craig Mundy$^{1}$ and Malcolm Haddon$^{1,2}$

1. Institute of Marine and Antarctic Science, University of Tasmania, P.O. Box 49, Hobart, Tasmania, Australia

2. CSIRO Oceans and Atmosphere, GPO Box 1538, Hobart, TAS 7001, Australia


# Abstract




# Introduction


* two sites, with a third for corroboration with four seasons months 1, 4, 8, and 11/12 for comaprison

* both sites exhibit the same sequence of change in exponential intercepts (_a_ parameter), when with 11/12 showing the largest L50 followed by month 1, month4 jumps to the smallest L50 and month 8 is half way between months 4 and 1.

* the difference in L50 across the four seasons was ~7.01mm when constant gradients were used and 7.27mm when both intercept and gradent were free to vary.






